config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  
  resources :users
  resources :sessions
  resources :categories, only: [:show]

  namespace :admin do
    resources :authors
    resources :books
    resources :categories
    resources :users, only: [:index, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :categorizations, dependent: :destroy
  has_many :authors, through: :categorizations

  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :description, length: { maximum: 500 }

  scope :order_by_date, -> { order(created_at: :desc) }
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :is_admin?
  
  def index
    @books = Book.all
  end

  def new
    @book = current_user.books.build
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to admin_books_path
      flash.now[:success] = "Successfully created a new book: #{@book.title}"
    else
      render "new"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      redirect_to admin_books_path
      flash.now[:success] = "Successfully updated a new book: #{@book.title}"
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to admin_books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :category_id, author_ids: [])
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
  def separate_by_comma(array)
    new_array = []
    array.each { |ele| new_array << ele.name }
    new_array.join(", ")
  end
end

app/views/admin/books/_book-list.html.erb
<% books.each do |book| %>
  <tr>
    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
      <p class="text-sm max-w-xs truncate leading-5 text-gray-900">
        <%= book.title %>
      </p>
    </td>
    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
      <p class="truncate max-w-xs">
        <%= separate_by_comma(book.authors) %>
      </p>
    </td>
    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
      <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
        <%= book.category.title %>
      </span>
    </td>
    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
      <%= display_date(book.created_at) %>
    </td>
    <td class="text-right px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 font-medium">
      <%= link_to "Edit", edit_admin_book_path(book.id), class: "text-indigo-600 hover:text-indigo-900" %>
      <%= link_to "Delete", admin_book_path(book.id), method: :delete, data: { confirm: "Are you sure?" }, class: "ml-2 text-red-600 hover:text-red-900" %>
    </td>
  </tr>
<% end %>

app/views/admin/books/_form.html.erb
<%= form_with(model: [:admin, @book], html: { multipart: true, data: { controller: "add-book" }, style: "min-height: calc(100vh - 64px)" }, class: "flex bg-white text-gray-900") do |form| %>
  <div class="w-full flex flex-col justify-between">
    <div class="mt-8 px-3 max-w-xl mx-auto w-full flex-1">
      <div>
        <%= form.text_field :title, placeholder: "Add a title", autocomplete: "off", class: "block w-full py-3 px-3 text-xl text-gray-900 font-medium border focus:outline-none border-transparent focus:border-gray-300" %>
      </div>
      <div>
        <%= form.text_area :description, placeholder: "Write a short description...", style: "height: calc(100vh - 240px)", class: "block w-full py-3 px-3 text-base overflow-y-auto resize-none border focus:outline-none border-transparent focus:border-gray-300" %>
      </div>
    </div>
    <div class="p-3 border-t z-50">
      <div class="flex items-center justify-end">
        <span class="shadow-sm rounded-md">
          <%= button_tag(class: "inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700 transition duration-150 ease-in-out") do  %>
            <svg class="-ml-1 mr-2 h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"></path></svg>
            <%= action_name == "new" ? "Publish" : "Save changes" %>
          <% end %>
        </span>
        <span class="ml-3 shadow-sm rounded-md">
          <button data-action="click->add-book#toggleSidebar" type="button" class="lg:hidden inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-md text-gray-700 bg-white hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:text-gray-800 active:bg-gray-50 active:text-gray-800 transition duration-150 ease-in-out">
            <svg class="-ml-1 mr-2 h-5 w-5 text-gray-500" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path><path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path></svg>
            Settings
          </button>
        </span>
      </div>
    </div>
  </div>
  <aside data-target="add-book.sidebar" class="add-book-sidebar-height absolute right-0 hidden lg:static lg:block bg-gray-50 max-w-xs w-full border-l border-gray-200">
    <div class="px-6 my-4">
      <div class="border-b border-gray-200">
        <button data-action="click->add-book#toggleAuthor" type="button" class="text-sm text-gray-700 font-medium py-3 w-full block inline-flex items-center justify-between focus:outline-none">
          <span>Author</span>
          <svg data-target="add-book.authorChevronIcon" class="h-4 w-4 transform transition duration-150 ease-in-out" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M19 9l-7 7-7-7"></path></svg>
        </button>
        <div data-target="add-book.authorContainer" class="mb-1 relative h-40 overflow-y-hidden flex flex-col">
          <div class="p-1 flex-shrink-0">
            <div class="relative">
              <input type="text" class="block w-full form-input pl-9 pr-3 text-sm h-9">
              <div class="absolute inset-y-0 flex items-center left-0 pl-3">
                <svg class="h-4 w-4 text-gray-500" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
              </div>
            </div>
          </div>
          <ul class="mt-2 text-sm flex-1 overflow-y-auto">
            <%= form.collection_check_boxes :author_ids, Author.all, :id, :name, class: "inline-flex items-center" do |c| %>
              <div class="px-2 py-1.5">
                <%= c.check_box class: "form-checkbox" %>
                <%= c.label class: "ml-1" %>
              </div>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="border-b border-gray-200">
        <button data-action="click->add-book#toggleCategory" type="button" class="text-sm text-gray-700 font-medium py-3 w-full block inline-flex items-center justify-between focus:outline-none">
          <span>Category</span>
          <svg data-target="add-book.categoryChevronIcon" class="h-4 w-4 transform transition duration-150 ease-in-out" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M19 9l-7 7-7-7"></path></svg>
        </button>
        <div data-target="add-book.categoryContainer" class="mb-1 relative h-40 overflow-y-hidden flex flex-col">
          <div class="p-1 flex-shrink-0">
            <div class="relative">
              <input type="text" class="block w-full form-input pl-9 pr-3 text-sm h-9">
              <div class="absolute inset-y-0 flex items-center left-0 pl-3">
                <svg class="h-4 w-4 text-gray-500" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
              </div>
            </div>
          </div>
          <ul class="mt-2 text-sm flex-1 overflow-y-auto">
            <%= form.collection_radio_buttons :category_id, Category.all, :id, :title, class: "inline-flex items-center" do |r| %>
              <div class="px-2 py-1.5">
                <%= r.radio_button class: "form-radio" %>
                <%= r.label class: "ml-1" %>
              </div>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </aside>
<% end %>

app/views/admin/books/edit.html.erb
<%= provide(:title, "Edit book") %>

<main>
  <%= render "form" %>
</main>

app/views/admin/books/index.html.erb
<%= provide(:title, "Book list") %>

<main style="min-height: calc(100vh - 64px)" class="bg-gray-100 p-6">
  <div class="sm:flex sm:items-center sm:justify-between">
    <div class="flex-1 min-w-0">
      <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
        Book list
      </h2>
    </div>
    <div class="mt-5 flex lg:mt-0 lg:ml-4">
      <span class="shadow-sm rounded-md">
        <%= link_to new_admin_book_path, class: "inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700 transition duration-150 ease-in-out" do %>
          <svg class="-ml-1 mr-2 h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 4v16m8-8H4"></path></svg>
          Add book
        <% end %>
      </span>
    </div>
  </div>

  <div class="my-16 shadow overflow-hidden sm:rounded-lg">
    <div class="align-middle inline-block w-full overflow-x-auto border-b border-gray-200">
      <table class="min-w-full">
        <thead>
          <tr>
            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              Title
            </th>
            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              Author
            </th>
            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              Category
            </th>
            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              Posted on
            </th>
            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50"></th>
          </tr>
        </thead>
        <tbody class="bg-white">
          <%= render "book-list", books: @books %>
        </tbody>
      </table>
    </div>
  </div>
</main>

app/views/admin/books/new.html.erb
<%= provide(:title, "Add book") %>

<main>
  <%= render "form" %>
</main>