config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  
  resources :users
  resources :sessions
  resources :categories, only: [:show]

  namespace :admin do
    resources :authors
    resources :books
    resources :categories
    resources :users, only: [:index, :destroy]
  end
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  scope :order_by_date, -> { order(created_at: :desc) }

  has_many :categorizations
  has_many :books, through: :categorizations

  DEFAULT_AUTHOR = "NA"

  def self.create_default_author
    if self.all.count == 0
      author = self.new(name: DEFAULT_AUTHOR, description: "System generated")
      author.save
    end
  end

  def self.move_to_default_author(del_author_id)
    books = Book.joins(:categorizations).where("categorizations.author_id" => del_author_id)
    if !books.nil?
      author = self.find_by(name: DEFAULT_AUTHOR)
      books.each do |book|
        book.categorizations.each do |indi_book|
          if indi_book.author_id == del_author_id
            indi_book.author_id = author.id
            indi_book.save
          end
        end
      end
    end
  end
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController
  before_action :is_admin?
  before_action :set_author, only: [:edit, :update, :destroy]
  before_action :is_default_author?, only: [:edit, :update, :destroy]

  def index
    @authors = Author.order_by_date
  end

  def new
    @author = Author.new
  end

  def create
    # create "NA" for default book instantiation.
    Author.create_default_author

    @author = Author.new(author_params)
    if @author.save
      redirect_to admin_authors_path
      flash.now[:success] = "Successfully created a new author: #{@author.name}"
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @author.update_attributes(author_params)
      redirect_to admin_authors_path
      flash.now[:success] = "Successfully updated author #{@author.name}"
    else
      render "edit"
    end
  end

  def destroy
    # before deleting the author, the books that are labelled with that author
    # should be moved to "NA".
    Author.move_to_default_author(@author.id)
    # after the book has been moved to the default author, we can then
    # delete the author.
    @author.destroy
    redirect_to admin_authors_path
  end

  private

  def author_params
    params.require(:author).permit(:name, :description)
  end

  def set_author
    @author = Author.find(params[:id])
  end

  def is_default_author?
    redirect_to admin_authors_path if @author.name == "NA"
  end
end

app/helpers/admin/authors_helper.rb
module Admin::AuthorsHelper
end

app/views/admin/authors/_author-list.html.erb
<% authors.each do |author| %>
  <tr>
    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-gray-900 text-sm max-w-xs truncate leading-5">
      <%= author.name %>
    </td>
    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
      <p class="truncate max-w-xs"><%= author.description %></p>
    </td>
    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
      <%= author.books.count %>
    </td>
    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
      <%= display_date(author.created_at) %>
    </td>
    <td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-200 text-sm leading-5 font-medium">
      <% if author.name != "NA" %>
        <%= link_to "Edit", edit_admin_author_path(author.id), class: "text-indigo-600 hover:text-indigo-900" %>
        <%= link_to "Delete", admin_author_path(author.id), method: :delete, data: { confirm: "Are you sure?" }, class: "ml-2 text-red-600 hover:text-red-900" %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/admin/authors/_form.html.erb
<%= form_with(model: [:admin, @author], class: "shadow mt-5 bg-white rounded-md p-4 md:mt-0 md:w-2/3 md:p-6") do |form| %>
  <div>
    <%= form.label :name, class: "text-sm text-gray-700 font-medium" %>
    <%= form.text_field :name, class: "form-input mt-1 block w-full px-3 py-2 shadow-sm", placeholder: "Eg: Paulo Coelho" %>
  </div>
  <div class="mt-4">
    <%= form.label :description, class: "text-sm text-gray-700 font-medium" %>
    <%= form.text_area :description, class: "form-input mt-1 block w-full px-3 py-2 shadow-sm", placeholder: "Write a short description about the author", rows: "10" %>
  </div>
  <div class="mt-5">
    <span class="shadow-sm rounded-md">
      <%= button_tag(class: "inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700 transition duration-150 ease-in-out") do  %>
        <svg class="-ml-1 mr-2 h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"></path></svg>
        <%= action_name == "new" ? "Publish" : "Save changes" %>
      <% end %>
    </span>
  </div>
<% end %>

app/views/admin/authors/edit.html.erb
<%= provide(:title, "Edit author") %>

<main style="min-height: calc(100vh - 64px)" class="bg-gray-100 p-6 relative">
  <div class="sm:flex sm:items-center sm:justify-between">
    <div class="flex-1 min-w-0">
      <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
        Edit author
      </h2>
    </div>
  </div>

  <div class="mt-5 md:flex md:mt-8 md:-ml-6">
    <div class="max-w-md md:w-1/3 xl:max-w-md md:px-6">
      <h2 class="text-gray-900 text-lg font-semibold">Author</h2>
      <p class="mt-2 text-sm text-gray-500 lg:text-base">
        Add an author that you think deserves the recognition.
      </p>
    </div>
    <%= render "form" %>
  </div>
</main>

app/views/admin/authors/index.html.erb
<%= provide(:title, "Author list") %>

<main style="min-height: calc(100vh - 64px)" class="bg-gray-100 p-6 relative">
  <div class="sm:flex sm:items-center sm:justify-between">
    <div class="flex-1 min-w-0">
      <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
        Author list
      </h2>
    </div>
    <div class="mt-5 flex lg:mt-0 lg:ml-4">
      <span class="shadow-sm rounded-md">
        <%= link_to new_admin_author_path, class: "inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700 transition duration-150 ease-in-out" do %>
          <svg class="-ml-1 mr-2 h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 4v16m8-8H4"></path></svg>
          Add author
        <% end %>
      </span>
    </div>
  </div>

  <div class="my-16 shadow overflow-hidden sm:rounded-lg">
    <div class="align-middle inline-block w-full overflow-x-auto border-b border-gray-200">
      <table class="min-w-full">
        <thead>
          <tr>
            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              Name
            </th>
            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              Description
            </th>
            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              Book count
            </th>
            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              Created on
            </th>
            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50"></th>
          </tr>
        </thead>
        <tbody class="bg-white">
          <%= render "author-list", authors: @authors %>
        </tbody>
      </table>
    </div>
  </div>
</main>

app/views/admin/authors/new.html.erb
<%= provide(:title, "Add author") %>

<main style="min-height: calc(100vh - 64px)" class="bg-gray-100 p-6 relative">
  <div class="sm:flex sm:items-center sm:justify-between">
    <div class="flex-1 min-w-0">
      <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
        Add author
      </h2>
    </div>
  </div>

  <div class="mt-5 md:flex md:mt-8 md:-ml-6">
    <div class="max-w-md md:w-1/3 xl:max-w-md md:px-6">
      <h2 class="text-gray-900 text-lg font-semibold">Author</h2>
      <p class="mt-2 text-sm text-gray-500 lg:text-base">
        Add an author that you think deserves the recognition.
      </p>
    </div>
    <%= render "form" %>
  </div>
</main>