config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  
  resources :users
  resources :sessions
  resources :categories, only: [:show]

  namespace :admin do
    resources :authors
    resources :books
    resources :categories
    resources :users, only: [:index, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  scope :order_by_date, -> { order(created_at: :desc) }

  has_many :categorizations
  has_many :books, through: :categorizations

  DEFAULT_AUTHOR = "NA"

  def self.create_default_author
    if self.all.count == 0
      author = self.new(name: DEFAULT_AUTHOR, description: "System generated")
      author.save
    end
  end

  def self.move_to_default_author(del_author_id)
    books = Book.joins(:categorizations).where("categorizations.author_id" => del_author_id)
    if !books.nil?
      author = self.find_by(name: DEFAULT_AUTHOR)
      books.each do |book|
        book.categorizations.each do |indi_book|
          if indi_book.author_id == del_author_id
            indi_book.author_id = author.id
            indi_book.save
          end
        end
      end
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :categorizations, dependent: :destroy
  has_many :authors, through: :categorizations

  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :description, length: { maximum: 500 }

  scope :order_by_date, -> { order(created_at: :desc) }
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, uniqueness: { case_sensitive: false }

  scope :order_by_date, -> { order(created_at: :desc) }

  has_many :books

  DEFAULT_CATEGORY = "Uncategorized"

  def self.create_default_category
    if self.all.count == 0
      category = self.new(title: DEFAULT_CATEGORY, description: "System generated")
      category.save
    end
  end

  def self.move_to_uncategorized(del_category_id)
    books = Book.where(category_id: del_category_id)
    if !books.nil?
      uncategorized = self.find_by(title: DEFAULT_CATEGORY)
      books.each do |book|
        book.category_id = uncategorized.id
        book.save
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  
  def log_in!(user)
    session[:user_id] = user.id
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user && @user.authenticate(params[:user][:password])
      log_in!(@user)
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @books = Book.all
    @categories = Category.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to root_url
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/admin/authors_helper.rb
module Admin::AuthorsHelper
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
  def separate_by_comma(array)
    new_array = []
    array.each { |ele| new_array << ele.name }
    new_array.join(", ")
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authenticate
    redirect_to root_url if current_user.nil?
  end

  def is_admin?
    redirect_to root_url if current_user.nil? || !current_user.admin?
  end

  def only_admin
    current_user && current_user.admin?
  end

  def render_header
    hide_controller = ["users", "sessions"]
    hide_action = ["new"]
    unless hide_controller.include?(controller.controller_name) && hide_action.include?(controller.action_name)
      render "layouts/header"
    end
  end

  def is_admin_page?
    # params[:controller].index("admin/") == 0
    controller.class.parents.include?(Admin)
  end

  def display_date(current_day)
    current_day.strftime("#{current_day.day.ordinalize} %b, %Y")
  end

  def title(page_title = "")
    base_title = "Book review app"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_admin-header.html.erb
<header data-controller="navbar" class="px-4 bg-white h-16 z-40 flex items-center shadow">
  <button data-action="click->sidebar-toggle#open" class="lg:hidden p-1 -ml-2 rounded-md text-gray-700 focus:outline-none focus:text-gray-900 focus:bg-gray-100 transition duration-150 ease-in-out">
    <svg class="h-6 w-6" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"></path></svg>
  </button>
  <div class="relative ml-auto">
    <div class="ml-3 relative">
      <div>
        <button data-action="click->navbar#profileToggle" class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-500 transition duration-150 ease-in-out" id="user-menu" aria-label="User menu" aria-haspopup="true">
          <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
        </button>
      </div>
      <div data-target="navbar.profile" class="hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg">
        <div class="py-1 rounded-md bg-white shadow-xs" role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
          <a href="#" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out">Your Profile</a>
          <a href="#" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out">Settings</a>
          <%= link_to "Sign out", session_path(current_user.id), method: "delete", class: "block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out" %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_header.html.erb
<div data-controller="navbar" class="relative bg-white">
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="flex justify-between items-center border-b-2 border-gray-100 py-3 md:justify-start md:space-x-10">
      <div class="lg:w-0 lg:flex-1">
        <%= link_to image_tag("logo-full.svg", class: "h-8 w-auto sm:h-10"), root_path %>
      </div>
      <div class="-mr-2 -my-2 md:hidden">
        <button data-action="click->navbar#open" type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
          <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
          </svg>
        </button>
      </div>
      <nav class="hidden md:flex space-x-10">
        <!-- Item active: "text-gray-900", Item inactive: "text-gray-500" -->
        <% if only_admin %>
          <%= link_to "Dashboard", admin_users_path, class: "text-base leading-6 font-medium text-gray-500 hover:text-gray-900 focus:outline-none focus:text-gray-900 transition ease-in-out duration-150" %>
        <% end %>
        <a href="#" class="text-base leading-6 font-medium text-gray-500 hover:text-gray-900 focus:outline-none focus:text-gray-900 transition ease-in-out duration-150">
          Pricing
        </a>
        <a href="#" class="text-base leading-6 font-medium text-gray-500 hover:text-gray-900 focus:outline-none focus:text-gray-900 transition ease-in-out duration-150">
          Docs
        </a>

        <div class="relative">
          <!-- Item active: "text-gray-900", Item inactive: "text-gray-500" -->
          <button type="button" class="text-gray-500 inline-flex items-center space-x-2 text-base leading-6 font-medium hover:text-gray-900 focus:outline-none focus:text-gray-900 transition ease-in-out duration-150">
            More
          </button>
        </div>
      </nav>
      <div class="hidden md:flex items-center justify-end space-x-8 md:flex-1 lg:w-0">
        <% if logged_in? %>
          <div class="ml-3 relative">
          <div>
            <button data-action="navbar#profileToggle" class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-500 transition duration-150 ease-in-out" id="user-menu" aria-label="User menu" aria-haspopup="true">
              <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
            </button>
          </div>
          <div data-target="navbar.profile" class="hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg">
            <div class="py-1 rounded-md bg-white shadow-xs" role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
              <a href="#" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out">Your Profile</a>
              <a href="#" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out">Settings</a>
              <%= link_to "Sign out", session_path(current_user.id), method: "delete", class: "block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out" %>
            </div>
          </div>
        </div>
        <% else %>
          <%= link_to "Sign in", new_session_path, class: "whitespace-no-wrap text-base leading-6 font-medium text-gray-500 hover:text-gray-900 focus:outline-none focus:text-gray-900" %>
          <span class="inline-flex rounded-md shadow-sm">
            <%= link_to "Sign up", new_user_path, class: "whitespace-no-wrap inline-flex items-center justify-center px-4 py-2 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150" %>
          </span>
        <% end %>
      </div>
    </div>
  </div>

  <!--
    Mobile menu, show/hide based on mobile menu state.
  -->
  <div data-target="navbar.mobile" class="hidden absolute top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
    <div class="rounded-lg shadow-lg">
      <div class="rounded-lg shadow-xs bg-white divide-y-2 divide-gray-50">
        <div class="pt-5 pb-6 px-5 space-y-6">
          <div class="flex items-center justify-between">
            <div>
              <%= image_tag("logo-mark.svg", class: "h-8 w-auto") %>
            </div>
            <div class="-mr-2">
              <button data-action="click->navbar#close" type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
                </svg>
              </button>
            </div>
          </div>
        </div>
        <div class="pb-6 px-5 space-y-6">
          <div class="grid grid-cols-2 row-gap-4 col-gap-8">
            <% if only_admin %>
              <%= link_to "Dashboard", admin_users_path, class: "text-base leading-6 font-medium text-gray-500 hover:text-gray-900 focus:outline-none focus:text-gray-900 transition ease-in-out duration-150" %>
            <% end %>
            <a href="#" class="text-base leading-6 font-medium text-gray-900 hover:text-gray-700 transition ease-in-out duration-150">
              Docs
            </a>
            <a href="#" class="text-base leading-6 font-medium text-gray-900 hover:text-gray-700 transition ease-in-out duration-150">
              Enterprise
            </a>
            <a href="#" class="text-base leading-6 font-medium text-gray-900 hover:text-gray-700 transition ease-in-out duration-150">
              Blog
            </a>
            <a href="#" class="text-base leading-6 font-medium text-gray-900 hover:text-gray-700 transition ease-in-out duration-150">
              Help Center
            </a>
            <a href="#" class="text-base leading-6 font-medium text-gray-900 hover:text-gray-700 transition ease-in-out duration-150">
              Guides
            </a>
            <a href="#" class="text-base leading-6 font-medium text-gray-900 hover:text-gray-700 transition ease-in-out duration-150">
              Security
            </a>
            <a href="#" class="text-base leading-6 font-medium text-gray-900 hover:text-gray-700 transition ease-in-out duration-150">
              Events
            </a>
          </div>
          <div class="space-y-6">
            <% if logged_in? %>
              <div class="grid grid-cols-2 row-gap-4 col-gap-8">
                <a href="#" class="text-base leading-6 font-medium text-gray-900 hover:text-gray-700 transition ease-in-out duration-150">
                  Profile
                </a>
                <a href="#" class="text-base leading-6 font-medium text-gray-900 hover:text-gray-700 transition ease-in-out duration-150">
                  Settings
                </a>
              </div>
              <span class="w-full flex rounded-md shadow-sm">
                <%= link_to "Log out", session_path(current_user.id), method: "delete", class: "w-full flex items-center justify-center px-4 py-2 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150" %>
              </span>
            <% else %>
              <span class="w-full flex rounded-md shadow-sm">
                <%= link_to "Sign up", new_user_path, class: "w-full flex items-center justify-center px-4 py-2 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150" %>
              </span>
              <p class="text-center text-base leading-6 font-medium text-gray-500">
                Existing customer?
                <%= link_to "Sign in", new_session_path, class: "text-indigo-600 hover:text-indigo-500 transition ease-in-out duration-150" %>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<aside data-target="sidebar-toggle.sidebar" class="transform -translate-x-full lg:translate-x-0 fixed top-0 lg:sticky w-64 z-50 h-screen overflow-y-hidden flex flex-col border-r border-gray-200 bg-white flex-shrink-0 transition duration-150 ease-in-out">
  <div class="h-16 flex flex-shrink-0 items-center justify-between px-3">
    <%= link_to image_tag("logo-full.svg", class: "h-8 w-auto"), root_path %>
    <button data-action="click->sidebar-toggle#close" class="lg:hidden p-1 -mr-2 rounded-md text-gray-700 focus:outline-none focus:text-gray-900 focus:bg-gray-100 transition duration-150 ease-in-out">
      <svg class="h-6 w-6" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M6 18L18 6M6 6l12 12"></path></svg>
    </button>
  </div>
  <div class="flex-1 overflow-y-auto">
    <nav class="mt-2 mb-4 px-1 text-gray-400 font-medium">
      <a href="#" class="mt-1 flex items-center hover:bg-gray-100 px-2 py-2 rounded transition duration-150 ease-in-out">
        <svg class="h-6 w-6" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
        <span class="pl-2 text-gray-600">Dashboard</span>
      </a>
      <%= link_to admin_books_path, class: "mt-1 flex items-center hover:bg-gray-100 px-2 py-2 rounded transition duration-150 ease-in-out" do %>
        <svg class="h-6 w-6" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"></path></svg>
        <span class="pl-2 text-gray-600">Books</span>
      <% end %>
      <%= link_to admin_authors_path, class: "mt-1 flex items-center hover:bg-gray-100 px-2 py-2 rounded transition duration-150 ease-in-out" do %>
        <svg class="h-6 w-6" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path></svg>
        <span class="pl-2 text-gray-600">Authors</span>
      <% end %>
      <%= link_to admin_categories_path, class: "mt-1 flex items-center hover:bg-gray-100 px-2 py-2 rounded transition duration-150 ease-in-out" do %>
        <svg class="h-6 w-6" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"></path></svg>
        <span class="pl-2 text-gray-600">Categories</span>
      <% end %>
      <%= link_to admin_users_path, class: "mt-1 flex items-center hover:bg-gray-100 px-2 py-2 rounded transition duration-150 ease-in-out" do %>
        <svg class="h-6 w-6" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"></path></svg>
        <span class="pl-2 text-gray-600">Users</span>
      <% end %>
    </nav>
  </div>
</aside>

<%# bg-gray-100 text-gray-700 %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title(yield :title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body class="min-h-screen font-sans text-gray-900 antialiased">
    <% if is_admin_page? %>
      <div data-controller="sidebar-toggle" class="flex">
        <%= render "layouts/sidebar" %>
        <div class="w-full flex flex-col">
          <%= render "layouts/admin-header" %>
          <%= yield %>
        </div>
      </div>
    <% else %>
      <%= render_header %>
      <%= yield %>
    <% end %>
  </body>
</html>